[tool.poetry]
name = "tts_dataset_processor"
version = "0.1.0"
description = "A tool to process raw audio files into a dataset suitable for TTS (Text-to-Speech) model training."
readme = "README.md"
packages = [{ include = "tts_dataset_processor", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
ten-vad = { git = "https://github.com/TEN-framework/ten-vad.git" }
audio-separator = { git = "https://github.com/kunibald413/python-audio-separator", extras = ["gpu"] }
numpy = ">=1.22,<2"
scipy = "^1.11.2"
pydub = "^0.25.1"
librosa = "^0.10.1"
soundfile = "^0.12.1"
nemo-toolkit = { version = "2.4.0", extras = ["asr"] }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"